---
# System configuration
system_user: ubbe
system_group: ubbe

# Monitoring stack versions
prometheus_version: "2.38.0"
prometheus_version_checksum: "43ddb515e1f3c28566aed0eba296bae136064e164ef0245986cfa9c497b839ce"

alertmanager_version: "0.24.0"
alertmanager_version_checksum: "6fa982232ae7be5524f5b3cd4e90b7c6a75086368200c917644eaa3e806555dc"

grafana_version: "9.1.0"
grafana_version_checksum: "ce245ae4bd882387e01afabc365c08c8ddb507b7156442ae7f7f9ef104d95cb0"

node_exporter_version: "1.3.1"
node_exporter_version_checksum: "68f3802c2dd3980667e4ba65ea2e1fb03f4a4ba026cca375f15a0390ff850949"

# Node exporter targets
node_exporter_targets:
  - 'localhost:9100'

# PagerDuty configuration
service_name: "luchian"
service_key: "dc81eb90081f430cd0e1e95a48b980a3"

# HTTP Basic Auth
http_basic_auth_username: "admin"
http_basic_auth_password: "password"

# Authentication settings for each service
enable_prometheus_auth: false
enable_alertmanager_auth: false
enable_node_exporter_auth: false

# Domain configuration
monitoring_domain: "monitoring.luchian.io"
grafana_hostname: "grafana"
prometheus_hostname: "prometheus"
alertmanager_hostname: "alertmanager"
node_exporter_hostname: "node-exporter"

# Nginx logrotate configuration
nginx_logrotate_scripts:
  - name: nginx
    path: /var/log/nginx/*.log
    rotate: 7
    size: 100M
    compress: true
    delaycompress: true
    missingok: true
    notifempty: true
    create: 644 www-data adm
    postrotate: "invoke-rc.d nginx rotate >/dev/null 2>&1"
