---
- name: Deploy Monitoring Stack
  hosts: monitoring
  become: true
  gather_facts: true

  vars:
    # System configuration
    common_system_user: ubbe
    common_system_group: ubbe

    # Grafana configuration
    grafana_system_user: ubbe
    grafana_system_group: ubbe

    # Node exporter configuration
    node_system_user: ubbe
    node_system_group: ubbe

    # Node exporter configuration
    node_exporter_system_user: ubbe
    node_exporter_system_group: ubbe

    # Prometheus configuration
    prometheus_system_user: ubbe
    prometheus_system_group: ubbe

    # Alertmanager configuration
    alertmanager_system_user: ubbe
    alertmanager_system_group: ubbe

    # Node exporter targets
    node_exporter_targets:
      - 'localhost:9100'
      - 'platform.luchian.io.local:9100' # Add this in /etc/hosts file to be the private IP of the platform server

    # Remote write configuration
    prometheus_remote_write_urls:
      - url: "http://localhost:9090/api/v1/write"
        username: "admin"
        password: "dc81eb90081f430cwryeydgredfae"

    # PagerDuty configuration
    alertmanager_service_name: "luchian"
    alertmanager_service_key: "dc81eb90081f430cd0e1e95a48b980a3"

    # HTTP Basic Auth
    http_basic_auth_username: "admin"
    http_basic_auth_password: "dc81eb90081f430coeiueue"

    # Authentication settings for each service
    enable_prometheus_auth: true
    enable_alertmanager_auth: true
    enable_node_exporter_auth: true

    # Domain configuration
    monitoring_domain: "monitoring.luchian.io"
    grafana_hostname: "grafana"
    prometheus_hostname: "prometheus"
    alertmanager_hostname: "alertmanager"
    node_exporter_hostname: "node-exporter"

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - role: common
    - role: node_exporter
    - role: prometheus
    - role: alertmanager
    - role: grafana
    - role: reverse_proxy

  post_tasks:
    - name: Display monitoring stack status
      ansible.builtin.debug:
        msg: |
          Monitoring stack deployment completed!
