---
- name: Deploy Monitoring Stack
  hosts: monitoring
  become: yes
  gather_facts: yes

  vars:
    # System configuration
    system_user: ubbe
    system_group: ubbe

    # Node exporter targets
    node_exporter_targets:
      - 'localhost:9100'
      - 'luchian.io:9100'

    # Remote write configuration
    prometheus_remote_write_urls:
      - url: "http://localhost:9090/api/v1/write"
        username: "admin"
        password: "password"

    # PagerDuty configuration
    service_name: "luchian"
    service_key: "dc81eb90081f430cd0e1e95a48b980a3"

    # HTTP Basic Auth
    http_basic_auth_username: "admin"
    http_basic_auth_password: "password"

    # Authentication settings for each service
    enable_prometheus_auth: true
    enable_alertmanager_auth: true
    enable_node_exporter_auth: true

    # Domain configuration
    monitoring_domain: "monitoring.luchian.io"
    grafana_hostname: "grafana"
    prometheus_hostname: "prometheus"
    alertmanager_hostname: "alertmanager"
    node_exporter_hostname: "node-exporter"

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - role: ../roles/common
    - role: ../roles/node_exporter
    - role: ../roles/prometheus
    - role: ../roles/alertmanager
    - role: ../roles/grafana
    - role: ../roles/reverse_proxy

  post_tasks:
    - name: Display monitoring stack status
      debug:
        msg: |
          Monitoring stack deployment completed!
