---
- name: Deploy Node Exporter
  hosts: hosts
  become: true
  gather_facts: true

  vars:
    # System configuration
    system_user: ubbe
    system_group: ubbe

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - role: node

  post_tasks:
    - name: Display node exporter deployment status
      ansible.builtin.debug:
        msg: |
          Node exporter deployment completed!
