# Copyright 2021 Uptimedog
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
  when: common_update_pkgs | bool
  tags: [ubbe, common]

- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400
  when: common_upgrade_pkgs | bool
  tags: [ubbe, common]

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
  when: common_upgrade_pkgs | bool
  tags: [ubbe, common]

- name: Create the system username
  ansible.builtin.user:
    name: "{{ common_system_user }}"
    state: present
    system: true
    shell: /sbin/nologin
    createhome: false
  tags: [ubbe, common]

- name: Create the system group
  ansible.builtin.group:
    name: "{{ common_system_group }}"
    system: true
    state: present
  tags: [ubbe, common]

- name: Add the system user to the system group
  ansible.builtin.user:
    name: "{{ common_system_user }}"
    group: "{{ common_system_group }}"
    state: present
  tags: [ubbe, common]

- name: Install basic package
  ansible.builtin.apt:
    pkg: ufw
    state: present
    update_cache: true
  tags: [ubbe, common]

- name: Install logrotate
  ansible.builtin.package:
    name: logrotate
    state: present
  tags: [ubbe, common]

- name: Install unzip package
  ansible.builtin.apt:
    pkg: unzip
    state: present
    update_cache: true
  tags: [ubbe, common]

- name: Disallow password authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart sshd
  tags: [ubbe, common]

- name: Activate firewall
  community.general.ufw:
    state: enabled
    policy: deny
  when: common_enable_fw
  tags: [ubbe, common]

- name: Firewall allow SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: common_enable_fw
  tags: [ubbe, common]

- name: Firewall allow HTTP
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: common_enable_fw
  tags: [ubbe, common]

- name: Firewall allow HTTPs
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
  when: common_enable_fw
  tags: [ubbe, common]

- name: Set motd banner
  ansible.builtin.template:
    src: "motd.j2"
    dest: "/etc/motd"
    mode: "0700"
  tags: [ubbe, common]
